// <auto-generated />
using BaGet.Tools.AzureSearchImporter.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;

namespace BaGet.Tools.AzureSearchImporter.Migrations
{
    [DbContext(typeof(IndexerContext))]
    partial class IndexerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("BaGet.Tools.AzureSearchImporter.Entities.PackageId", b =>
                {
                    b.Property<int>("Key")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Done");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT COLLATE NOCASE");

                    b.HasKey("Key");

                    b.HasIndex("Done");

                    b.HasIndex("Value")
                        .IsUnique();

                    b.ToTable("PackageIds");
                });
#pragma warning restore 612, 618
        }
    }
}
