# REST Client tests on https://github.com/tronalddump-io/tronald-app
@baseUrl = http://localhost:50561

### Get package
GET {{baseUrl}}/v3/registration/Divelements.SandDock/index.json
Accept: application/json