// Global using directives

global using System.Collections.Concurrent;
global using System.ComponentModel.DataAnnotations;
global using System.Globalization;
global using System.Net;
global using System.Reflection;
global using System.Reflection.Metadata;
global using System.Security.Cryptography;
global using System.Text.Json.Serialization;
global using BaGet.Core;
global using BaGet.Protocol;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.ChangeTracking;
global using Microsoft.EntityFrameworkCore.Infrastructure;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.DependencyInjection.Extensions;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using Newtonsoft.Json;
global using Newtonsoft.Json.Linq;
global using NuGet.Common;
global using NuGet.Configuration;
global using NuGet.Frameworks;
global using NuGet.Packaging;
global using NuGet.Protocol;
global using NuGet.Protocol.Core.Types;
global using NuGet.Versioning;
global using static NuGet.Frameworks.FrameworkConstants;