//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaGet.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BaGet.Tests.TestData.TestData", typeof(TestData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;version&quot;:&quot;3.0.0&quot;,&quot;resources&quot;:[{&quot;@id&quot;:&quot;http://localhost/api/v2/package&quot;,&quot;@type&quot;:&quot;PackagePublish/2.0.0&quot;},{&quot;@id&quot;:&quot;http://localhost/api/v2/symbol&quot;,&quot;@type&quot;:&quot;SymbolPackagePublish/4.9.0&quot;},{&quot;@id&quot;:&quot;http://localhost/v3/search&quot;,&quot;@type&quot;:&quot;SearchQueryService&quot;},{&quot;@id&quot;:&quot;http://localhost/v3/search&quot;,&quot;@type&quot;:&quot;SearchQueryService/3.0.0-beta&quot;},{&quot;@id&quot;:&quot;http://localhost/v3/search&quot;,&quot;@type&quot;:&quot;SearchQueryService/3.0.0-rc&quot;},{&quot;@id&quot;:&quot;http://localhost/v3/registration&quot;,&quot;@type&quot;:&quot;RegistrationsBaseUrl&quot;},{&quot;@id&quot;:&quot;http://localhost/v3/registrat [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ServiceIndex {
            get {
                return ResourceManager.GetString("ServiceIndex", resourceCulture);
            }
        }
    }
}
