{{- if .Values.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.fullname }}
  {{- if .Values.namespaceOverride }}
  namespace: {{ .Values.namespaceOverride }}
  {{- end }}
  labels:
    {{- include "ui.labels" . | nindent 4 }}
spec:
  rules:
  {{ range .Values.ingress.hosts }}
  - host: {{ .name }}
    http:
      paths:
      - path: /
        backend:
          {{- if $.Values.service.serviceName }}
          serviceName: {{ $.Values.service.serviceName }}
          {{- else }}
          serviceName: {{ $.Values.fullname }}-svc
          {{- end }}
          servicePort: {{ $.Values.service.targetPort }}
  {{- end }}
  {{ range .Values.ingress.hosts }}
  {{- if .tls }}
  tls:
  - hosts:
    - {{ .name }}
    secretName: {{ .secret }}
  {{- end }}
  {{- end -}}
{{- end -}}